runninghub:
  host: "https://www.runninghub.cn"
  api_key: "xxx"
  ai_app_webapp_id: "1973555977595301890"
  ai_app_api_key: "xxxx"
  ai_app_webapp_img_id: "1976487269899046914"
  max_concurrent_slots: 3  # RunningHub 最大并发槽位数量
# Server configuration
server:
  host: "http://ailive.perseids.cn:11442"
  port: 5178
  
# Default timeout settings
timeout:
  request_timeout: 10000
  status_check_timeout: 900
  status_check_interval: 10

authentication:
  url: "http://192.168.10.212:xxx/api/v1"

# Database configuration
database:
  host: "192.168.10.212"
  port: 3306
  user: "voice_replace_debug_admin"
  password: "xxx"
  database: "voice_replace_debug"
  charset: "utf8mb4"

# AI Tools configuration
ai_tools:
  token: "b8733e482d434746becc44ea38c414a5"

duomi:
  token: "xxx"

bin:
  ffmpeg: "/usr/bin/ffmpeg"
  ffprobe: "/usr/bin/ffprobe"

# LLM configuration
llm:
  baidu:
    api_key: "bce-v3/xxxx"
    api_url: "https://qianfan.baidubce.com/v2/chat/completions"
    model: "ernie-4.5-turbo-vl-latest"
  qwen:
    api_key: "sk-xxxx"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen-plus"

# Test mode configuration
test_mode:
  enabled: false  # 是否启用测试模式
  mock_videos:
    image_to_video: "https://cdn3.dmiapi.com/attachments/sora/20260107/968e1cf718e6e115fdb0a5874d39c470.mp4?e=1768198067&token=mTvq9hVVEUusCokO8WegAYo2IjxRSvr97Q4j2lrx:LWFb2h3-ecBwr-YBQWToVPcEkJw="  # 图生视频的测试视频URL
    text_to_video: "https://cdn3.dmiapi.com/attachments/sora/20260107/968e1cf718e6e115fdb0a5874d39c470.mp4?e=1768198067&token=mTvq9hVVEUusCokO8WegAYo2IjxRSvr97Q4j2lrx:LWFb2h3-ecBwr-YBQWToVPcEkJw="  # 文生视频的测试视频URL
  mock_images:
    image_edit: "https://cdn3.dmiapi.com/attachments/gemini/20260107/636584241e053a19c784b4c1ac6a4c83.png?e=1768198099&token=mTvq9hVVEUusCokO8WegAYo2IjxRSvr97Q4j2lrx:cPKvpbphxp-XZGU8630BEA_zcos="  # 图片编辑的测试图片URL
    text_to_image: "https://cdn3.dmiapi.com/attachments/gemini/20260107/636584241e053a19c784b4c1ac6a4c83.png?e=1768198099&token=mTvq9hVVEUusCokO8WegAYo2IjxRSvr97Q4j2lrx:cPKvpbphxp-XZGU8630BEA_zcos="  # 文生图的测试图片URL