runninghub:
  host: "https://www.runninghub.cn"
  api_key: "xxx"
  ai_app_webapp_id: "1973555977595301890"
  ai_app_api_key: "xxxx"
  ai_app_webapp_img_id: "1976487269899046914"
# Server configuration
server:
  host: "http://ailive.perseids.cn:11442"
  port: 5178
  
# Default timeout settings
timeout:
  request_timeout: 10000
  status_check_timeout: 900
  status_check_interval: 10

authentication:
  url: "http://192.168.10.212:xxx/api/v1"

# Database configuration
database:
  host: "192.168.10.212"
  port: 3306
  user: "voice_replace_debug_admin"
  password: "xxx"
  database: "voice_replace_debug"
  charset: "utf8mb4"

# AI Tools configuration
ai_tools:
  token: "b8733e482d434746becc44ea38c414a5"

duomi:
  token: "xxx"

bin:
  ffmpeg: "/usr/bin/ffmpeg"
  ffprobe: "/usr/bin/ffprobe"

# LLM configuration
llm:
  baidu:
    api_key: "bce-v3/xxxx"
    api_url: "https://qianfan.baidubce.com/v2/chat/completions"
    model: "ernie-4.5-turbo-vl-latest"
  qwen:
    api_key: "sk-xxxx"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen-plus"